### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by yulu0724** [salesforce/morpheus#1]
Hi, may I know your python version? I always have problems when installing the requirement.

Collecting lemminflect==0.2.1 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/a9/2d/473d98e5401601f5ff99bd93655ff5651655bf46a086316a3624ce475d42/lemminflect-0.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-nmRwpu/lemminflect/setup.py", line 10, in <module>
        from lemminflect import __version__
      File "lemminflect/__init__.py", line 3, in <module>
        from   .core.Inflections import Inflections
      File "lemminflect/core/Inflections.py", line 4, in <module>
        from   .InflectionRules  import InflectionRules, MorphologyStyleModel
      File "lemminflect/core/InflectionRules.py", line 3, in <module>
        from   ..kmodels.KInfer import getKInferInstance
      File "lemminflect/kmodels/KInfer.py", line 1, in <module>
        from   abc import ABC, abstractmethod
    ImportError: cannot import name ABC
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-nmRwpu/lemminflect/

Thanks!

**Comment by samsontmr** [comment]
Hi, it should have been either 3.5 or 3.6. It seems you might be using a version that doesn't have the [abc](https://docs.python.org/3/library/abc.html) module.
